version: "3.3"
services:
  redis:
    image: redis:latest
    command: ["redis-server", "/config/redis.conf"]
    volumes:
      - "./config/redis:/config:ro"
      - "/srv/docker/redis:/data"
    networks:
      - dbnet
  bot:
    build: .
    volumes:
      - "/srv/docker/bot:/out/Configs:ro"
    networks:
      - dbnet
    depends_on:
      - redis
    restart: on-failure
networks:
  dbnet:
