version: "3.3"
services:
  redis:
    image: redis:latest
    command: ["redis-server", "/config/redis.conf"]
    volumes:
      - "./config/redis:/config:ro"
      - "./.data/redis:/data"
    ports:
      - "6379:6379"
    networks:
      - dbnet
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - dbnet
networks:
  dbnet:
